{
 "title": "Azure Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage - Azure App Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "azure_appservice_cpu_time{resource=\"/subscriptions/3bff15a8-79cf-44d3-b98f-94606c8f3a60/resourceGroups/rg-dev/providers/Microsoft.Web/sites/app-web-ztg2yzezngfmy\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Memory Usage - Azure App Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "azure_appservice_memory_working_set{resource=\"/subscriptions/3bff15a8-79cf-44d3-b98f-94606c8f3a60/resourceGroups/rg-dev/providers/Microsoft.Web/sites/app-web-ztg2yzezngfmy\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Request Count - Azure App Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "azure_appservice_request_count_total{resource=\"/subscriptions/3bff15a8-79cf-44d3-b98f-94606c8f3a60/resourceGroups/rg-dev/providers/Microsoft.Web/sites/app-web-ztg2yzezngfmy\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}